/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;

/**
 *
 * @author mark
 */
public class AntSelectUI extends javax.swing.JFrame {
    private static Controller myController;
    
    /**
     * Creates new form AntSelectUI
     */
    public AntSelectUI(Controller c) {
        //this.myController = c;
        myController = c;
        initComponents();
        //myController.addAntSelectView(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ant1Button = new javax.swing.JButton();
        ant0Button = new javax.swing.JButton();
        ant3Button = new javax.swing.JButton();
        ant2Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Azbil GUI: Antenna Selection Screen (Top)");

        ant1Button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ant1Button.setText("ANTENNA PORT 1");
        ant1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ant1ButtonActionPerformed(evt);
            }
        });

        ant0Button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ant0Button.setText("ANTENNA PORT 0");
        ant0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ant0ButtonActionPerformed(evt);
            }
        });

        ant3Button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ant3Button.setText("ANTENNA PORT 3");
        ant3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ant3ButtonActionPerformed(evt);
            }
        });

        ant2Button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ant2Button.setText("ANTENNA PORT 2");
        ant2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ant2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(721, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ant3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ant1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(ant0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(698, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(ant2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(691, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(ant1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(ant3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(ant0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(590, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(490, Short.MAX_VALUE)
                    .addComponent(ant2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(294, 294, 294)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ant2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ant2ButtonActionPerformed
        // TODO add your handling code here:
        //new AntDataUI(myController).setVisible(true);
    }//GEN-LAST:event_ant2ButtonActionPerformed

    private void ant3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ant3ButtonActionPerformed
        // TODO add your handling code here:
        //new AntDataUI(myController).setVisible(true);
    }//GEN-LAST:event_ant3ButtonActionPerformed

    private void ant0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ant0ButtonActionPerformed
        // TODO add your handling code here:
        //new AntDataUI(myController).setVisible(true);
    }//GEN-LAST:event_ant0ButtonActionPerformed

    private void ant1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ant1ButtonActionPerformed
        // TODO add your handling code here:
        //new AntDataUI(myController).setVisible(true);
    }//GEN-LAST:event_ant1ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AntSelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AntSelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AntSelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AntSelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AntSelectUI(myController).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ant0Button;
    private javax.swing.JButton ant1Button;
    private javax.swing.JButton ant2Button;
    private javax.swing.JButton ant3Button;
    // End of variables declaration//GEN-END:variables
}
