/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;

/**
 *
 * @author mark
 */
public class SetupSelectUI extends javax.swing.JFrame {

    private static Controller myController;
    
    /**
     * Creates new form SetupSelectUI
     */
    public SetupSelectUI(Controller c) {
        myController = c;
        initComponents();
        myController.addSetupSelView(this);
    }
    
    public int getScreenRefreshRateInSecs() {
        int myInt = 0;
        myInt = screenRefreshComboBox.getSelectedIndex();
        myInt++;  //index 0-9 for values 1-10 seconds
        return (myInt);
    }
    
    public void setScreenRefreshRateInSecs(int myInt) {
        // index 0-9 for values 1-10 seconds
        if (myInt < 1 | myInt > 10) {
            myInt = 1;  // 1 sec
        }
        myInt--;  // change range to 0-9
        screenRefreshComboBox.setSelectedIndex(myInt);
    }
    
    public static ReaderReadRates intToEnumReaderReadRate(int myInt) {
        switch (myInt) {
            case 0: return ReaderReadRates.readerRate250ms;       // zero to enum 1 (starting enum value in java)
            case 1: return ReaderReadRates.readerRate500ms;
            case 2: return ReaderReadRates.readerRate1sec;
            default: return ReaderReadRates.readerRate250ms;
        }
    }
   
    public ReaderReadRates getReaderReadRate() {
        return intToEnumReaderReadRate(readerReadRateComboBox.getSelectedIndex());  // convert int to enum 
    }
    
    public void setReaderReadRate(ReaderReadRates myEnum) {
        // index 0-2 for values 250, 500 & 1000 ms
        int myInt = myEnum.ordinal();
        readerReadRateComboBox.setSelectedIndex(myInt);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        readerReadRateComboBox = new javax.swing.JComboBox<>();
        readerReadRateLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        antSetupButton = new javax.swing.JButton();
        tagSetupButton1 = new javax.swing.JButton();
        screenRefreshLabel1 = new javax.swing.JLabel();
        screenRefreshComboBox = new javax.swing.JComboBox<>();

        setTitle("Setup-Selection");

        readerReadRateComboBox.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        readerReadRateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "250", "500", "1000" }));
        readerReadRateComboBox.setActionCommand("readerReadRateComboBoxChanged");
        readerReadRateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerReadRateComboBoxActionPerformed(evt);
            }
        });

        readerReadRateLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        readerReadRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        readerReadRateLabel.setText("Reader Read Rate in ms:");

        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.setActionCommand("ButtonSetupSelBack");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        antSetupButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        antSetupButton.setText("Antenna Setup");
        antSetupButton.setActionCommand("ButtonAntSetup");
        antSetupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antSetupButtonActionPerformed(evt);
            }
        });

        tagSetupButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tagSetupButton1.setText("Tag Setup");
        tagSetupButton1.setActionCommand("ButtonTagSetup");
        tagSetupButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagSetupButton1ActionPerformed(evt);
            }
        });

        screenRefreshLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        screenRefreshLabel1.setText("Screen Refresh Rate in Seconds (1-10):");

        screenRefreshComboBox.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        screenRefreshComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        screenRefreshComboBox.setActionCommand("screenRefreshComboBoxChanged");
        screenRefreshComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenRefreshComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 257, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tagSetupButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(antSetupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(290, 290, 290))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(screenRefreshLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(screenRefreshComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(readerReadRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(readerReadRateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(screenRefreshComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(screenRefreshLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(readerReadRateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readerReadRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(tagSetupButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(antSetupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tagSetupButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagSetupButton1ActionPerformed
        // TODO add your handling code here:
        myController.guiActionPerformed(evt);
        //new TagSetupUI().setVisible(true);
    }//GEN-LAST:event_tagSetupButton1ActionPerformed

    private void antSetupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antSetupButtonActionPerformed
        // TODO add your handling code here:
        myController.guiActionPerformed(evt);
        //new AntSetupUI().setVisible(true);
    }//GEN-LAST:event_antSetupButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        myController.guiActionPerformed(evt);
        //setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void readerReadRateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readerReadRateComboBoxActionPerformed
        // TODO add your handling code here:
        myController.guiActionPerformed(evt);
    }//GEN-LAST:event_readerReadRateComboBoxActionPerformed

    private void screenRefreshComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenRefreshComboBoxActionPerformed
        // TODO add your handling code here:
        myController.guiActionPerformed(evt);
    }//GEN-LAST:event_screenRefreshComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetupSelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetupSelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetupSelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetupSelectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupSelectUI(myController).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antSetupButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> readerReadRateComboBox;
    private javax.swing.JLabel readerReadRateLabel;
    private javax.swing.JComboBox<String> screenRefreshComboBox;
    private javax.swing.JLabel screenRefreshLabel1;
    private javax.swing.JButton tagSetupButton1;
    // End of variables declaration//GEN-END:variables
}
